# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160329_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id', '-updated']},
        ),
    ]
